(ns org.apache.commons.math4.stat.descriptive.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.math4.stat.descriptive.AbstractStorelessUnivariateStatistic])
(require '[org.apache.commons.math4.stat.descriptive.AbstractUnivariateStatistic])
(require '[org.apache.commons.math4.stat.descriptive.AggregateSummaryStatistics])
(require '[org.apache.commons.math4.stat.descriptive.DescriptiveStatistics])
(require '[org.apache.commons.math4.stat.descriptive.MultivariateSummaryStatistics])
(require '[org.apache.commons.math4.stat.descriptive.StatisticalMultivariateSummary])
(require '[org.apache.commons.math4.stat.descriptive.StatisticalSummary])
(require '[org.apache.commons.math4.stat.descriptive.StatisticalSummaryValues])
(require '[org.apache.commons.math4.stat.descriptive.StorelessUnivariateStatistic])
(require '[org.apache.commons.math4.stat.descriptive.SummaryStatistics])
(require '[org.apache.commons.math4.stat.descriptive.SynchronizedDescriptiveStatistics])
(require '[org.apache.commons.math4.stat.descriptive.SynchronizedMultivariateSummaryStatistics])
(require '[org.apache.commons.math4.stat.descriptive.SynchronizedSummaryStatistics])
(require '[org.apache.commons.math4.stat.descriptive.UnivariateStatistic])
(require '[org.apache.commons.math4.stat.descriptive.WeightedEvaluation])
