(ns org.apache.commons.math4.analysis.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.math4.analysis.BivariateFunction])
(require '[org.apache.commons.math4.analysis.FunctionUtils])
(require '[org.apache.commons.math4.analysis.MultivariateFunction])
(require '[org.apache.commons.math4.analysis.MultivariateMatrixFunction])
(require '[org.apache.commons.math4.analysis.MultivariateVectorFunction])
(require '[org.apache.commons.math4.analysis.ParametricUnivariateFunction])
(require '[org.apache.commons.math4.analysis.RealFieldUnivariateFunction])
(require '[org.apache.commons.math4.analysis.TrivariateFunction])
(require '[org.apache.commons.math4.analysis.UnivariateFunction])
(require '[org.apache.commons.math4.analysis.UnivariateMatrixFunction])
(require '[org.apache.commons.math4.analysis.UnivariateVectorFunction])
