(ns org.apache.commons.math4.analysis.interpolation.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.math4.analysis.interpolation.AkimaSplineInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.BicubicInterpolatingFunction])
(require '[org.apache.commons.math4.analysis.interpolation.BicubicInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.BivariateGridInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.DividedDifferenceInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.FieldHermiteInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.HermiteInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.InterpolatingMicrosphere])
(require '[org.apache.commons.math4.analysis.interpolation.InterpolatingMicrosphere2D])
(require '[org.apache.commons.math4.analysis.interpolation.LinearInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.LoessInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.MicrosphereProjectionInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.MultivariateInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.NevilleInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.PiecewiseBicubicSplineInterpolatingFunction])
(require '[org.apache.commons.math4.analysis.interpolation.PiecewiseBicubicSplineInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.SplineInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.TricubicInterpolatingFunction])
(require '[org.apache.commons.math4.analysis.interpolation.TricubicInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.TrivariateGridInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.UnivariateInterpolator])
(require '[org.apache.commons.math4.analysis.interpolation.UnivariatePeriodicInterpolator])
